FROM node:alpine AS base
RUN apk -U add curl
WORKDIR /usr/src/app
EXPOSE 3001
FROM node:argon AS build
WORKDIR /usr/src/app
# 앱 종속성 설치
COPY package.json /usr/src/app/
RUN npm install
# 앱 소스 번들
COPY . /usr/src/app
FROM base AS final
WORKDIR /usr/src/app
COPY --from=build /usr/src/app .
CMD [ "npm", "start" ]
